RazorPages1/RazorPages1/Components/AlumnoCursoViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using RazorPages.Modelos;
using RazorPages.Service;

namespace RazorPages1.Components
{
    public class AlumnoCursoViewComponent : ViewComponent
//subclase de ViewComponent que está dentro de AspNetCore.Mvc, es obligatorio que el nombre de la clase acabe con ViewComponent
	{
        public IAlumnoRepositorio AlumnoRepositorio { get; }

		public AlumnoCursoViewComponent(IAlumnoRepositorio alumnoRepositorio)
		{
            AlumnoRepositorio = alumnoRepositorio;
        }

        //el metodo invoque es el método que se ejecuta en el ciclo de vida de un ViewComponent, como sería el onGet de las PageModel
        public IViewComponentResult Invoke(Curso? curso = null) //puede recibir un objto curso o no, en ese caso será null
        {
            
            var resultado = AlumnoRepositorio.AlumnosPorCurso(curso);
            return View(resultado);
        }
    }
}

RazorPages1/RazorPages1/Pages/Alumnos/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Modelos;
using RazorPages.Service;

namespace RazorPages1.Pages.Alumnos
{
	public class DeleteModel : PageModel
    {
        //declaramos un atributo de clase de la clase IAlumnoRepositorio para poder llamar al método GetAlumnoById
        private readonly IAlumnoRepositorio alumnoRepositorio;

        [BindProperty]//esto permite que se actualice
        public Alumno alumno { get; set; }


        public DeleteModel(IAlumnoRepositorio alumnoRepositorio, IWebHostEnvironment webHostEnvironment)
        {
            this.alumnoRepositorio = alumnoRepositorio;
           
        }
        public void OnGet(int id)
        {
            alumno = alumnoRepositorio.GetAlumnoById(id);

        }
        public IActionResult OnPost(int id)
        {
            alumnoRepositorio.Delete(id);
            return RedirectToPage("Index");
        }
            
           
        
    }
}

RazorPages1/RazorPages1/Pages/Alumnos/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Modelos;
using RazorPages.Service;

namespace RazorPages1.Pages.Alumnos
{
    public class EditModel : PageModel
    {
        //declaramos un atributo de clase de la clase IAlumnoRepositorio para poder llamar al método GetAlumnoById
        private readonly IAlumnoRepositorio alumnoRepositorio;
        public IWebHostEnvironment WebHostEnvironment { get; }//en el destornillador crear y asignar la propiedad

        [BindProperty]//esto permite que se actualice
        public Alumno alumno { get; set; }

        //el atributo Photo de la clase IFormFile que es diferente del atributo Foto de la clase Alumno
        [BindProperty]
        public IFormFile Photo { get; set; }
        

        public EditModel(IAlumnoRepositorio alumnoRepositorio, IWebHostEnvironment webHostEnvironment)
        {
            this.alumnoRepositorio = alumnoRepositorio;
            WebHostEnvironment = webHostEnvironment;
        }
        //se ejecuta siempre al cargar la página a no ser que se haya espeficado que se envían los parámetros con el post
        //le decimos que puede recibir o no un int
        public IActionResult OnGet(int? id)
        {
            if (id.HasValue)
            {
                //para que no de error, porque id no sabemos lo que es, le decimos que coja el valor
                alumno = alumnoRepositorio.GetAlumnoById(id.Value);
            }
            else
            {
                alumno = new Alumno();
            }
            return Page();   
        }
        //cuando demos al botón de submit se ejecutará éste metodo
        //en vez de void, va a devolver una acción
        public IActionResult OnPost(Alumno alumno)
        {
            if (ModelState.IsValid)//si he rellenado todos los campos required
            {
                if (Photo != null)
                {
                    {
                        if(alumno.Foto != null)
                        {
                            string filePath = Path.Combine(WebHostEnvironment.WebRootPath, "images", alumno.Foto);
                            System.IO.File.Delete(filePath);
                        }
                    }
                    alumno.Foto = ProcessUploadedFile();
                }
                if (alumno.Id != 0)
                    alumnoRepositorio.Update(alumno);
                else
                    alumnoRepositorio.Add(alumno);
                return RedirectToPage("Index");
            }else
                return Page();
        }

        private string ProcessUploadedFile()
        {
            //necesitamos un objeto de una clase que sea capaz de manipular el proyecto por lo que la creamos en el constructor
            string uploadsFolder = Path.Combine(WebHostEnvironment.WebRootPath, "images");//lo primero nos devuelve el path a wwwroot
            string filePath = Path.Combine(uploadsFolder, Photo.FileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                Photo.CopyTo(fileStream);
            }
            return Photo.FileName;
        }
    }
}

RazorPages1/RazorPages1/Pages/Alumnos/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Modelos;
using RazorPages.Service;
using System.Runtime.CompilerServices;

namespace RazorPages1.Pages.Alumnos
{
    public class IndexModel : PageModel
    {
        //declaramos un atributo de clase de la clase IAlumnoRepositorio para poder llamar al método GetAllAlumnos
        private readonly IAlumnoRepositorio alumnoRepositorio;
        //para que salga IAlumnoRepositorio añado la dependencia del .Service 
        // y uso este objeto para llamar al método GetAllAlumnos()
        public IEnumerable<Alumno> Alumnos;
        //cuando llamemos al GetAllAlumnos nos devolverá una lista de objetos de la clase Alumno, por lo que creamos 
        //un objeto de esa clase para poder llamarlo.


        //[BindProperty(SupportsGet = true)]//lo relacionamos con el de la pagina web "elementoAMostrar" ahora lo hacemos sin ello
        public string elementoABuscar { get; set; } 
        

        public IndexModel(IAlumnoRepositorio alumnoRepositorio) 
        {
            this.alumnoRepositorio = alumnoRepositorio;
            /*esto es inyección de dependencias:
            * que sin llamar explicitamente a los métodos constructores
            * se creen */
        }
        public void OnGet(string elementoABuscar = "")
        {
            Alumnos = alumnoRepositorio.FindAlumnos(elementoABuscar);
        }
    }
}

RazorPages1/RazorPages1/Pages/Alumnos/Index2.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Modelos;
using RazorPages.Service;
using System.Runtime.CompilerServices;

namespace RazorPages1.Pages.Alumnos
{
    public class Index2Model : PageModel
    {
        //declaramos un atributo de clase de la clase IAlumnoRepositorio para poder llamar al método GetAllAlumnos
        private readonly IAlumnoRepositorio alumnoRepositorio;
        //para que salga IAlumnoRepositorio añado la dependencia del .Service 
        // y uso este objeto para llamar al método GetAllAlumnos()
        public IEnumerable<Alumno> Alumnos;
        //cuando llamemos al GetAllAlumnos nos devolverá una lista de objetos de la clase Alumno, por lo que creamos 
        //un objeto de esa clase para poder llamarlo.
        public Curso Curso;

        [BindProperty(SupportsGet = true)]//lo relacionamos con el de la pagina web "elementoAMostrar" ahora lo hacemos sin ello
        public Curso elementoABuscar { get; set; } 
        

        public Index2Model(IAlumnoRepositorio alumnoRepositorio) 
        {
            this.alumnoRepositorio = alumnoRepositorio;
            /*esto es inyección de dependencias:
            * que sin llamar explicitamente a los métodos constructores
            * se creen */
        }
        public void OnGet()
        {
            Alumnos = alumnoRepositorio.FindAlumnosByCurso(elementoABuscar);
        }
    }
}

RazorPages1/RazorPages1/Pages/Alumnos/Delete.cshtml
@page
@model RazorPages1.Pages.Alumnos.DeleteModel
@{
}

<h1>Confirmación de borrado</h1>
<div class="alert alert-danger">
    <h5>Esás seguro de que quieres eliminar al alumno - @Model.alumno.Nombre</h5>
        <form method="post">
            <!--input type="hidden" asp-for="alumno.Id" /> No hace falta porque tenemos el BindProperty en alumno-->
            <button type="submit" class="btn btn-danger">Si</button>
            <a asp-page="/Alumnos/Index" class="btn btn-primary">No</a>
        </form>
</div>

RazorPages1/RazorPages1/Pages/Alumnos/Details.cshtml
@page
@model RazorPages1.Pages.Alumnos.DetailsModel
@{
    //usamos Model.alumno para acceder al objeto alumno que está dentro de la clase
    var photo = "~/images/" + (Model.alumno.Foto ?? "noimage.jpg");
}
<div class="col-sm-8">
    <!--await Component.InvokeAsync("AlumnosCursoContar")-->
    @await Component.InvokeAsync("AlumnoCurso", new { curso = Model.alumno.CursoId })
</div>

<div class="card m-3" align="center" style="min-width: 12rem; max-width:80%">
    <div class="card-header">
        <h3>@Model.alumno.Nombre</h3>
    </div>
    <img class="card-img-top" width="250px" asp-append-version="true" src="@photo">
    <div class="card-footer text-center">
        <h3>Id: @Model.alumno.Id</h3>
        <h3>Email: @Model.alumno.Email</h3>
        <h3>Curso: @Model.alumno.CursoId</h3>
    </div>
    <!--Prueba de commit-->

</div>

RazorPages1/RazorPages1/Pages/Alumnos/Edit.cshtml
@page
@model RazorPages1.Pages.Alumnos.EditModel
@{
    //Antes de abrirse la página se ejecuta el controlador (Edit.cshtml.cs)
    //usamos Model.alumno para acceder al objeto alumno que está dentro de la clase
    var photo = "~/images/" + (Model.alumno.Foto ?? "noimage.jpg");
    var titulo = Model.alumno.Id > 0 ? "Edición datos " : "Creación ";

}

<h1 align="center"> @titulo de alumno</h1>
<form method="post" class="mt-3" enctype="multipart/form-data">
    <!--hay que añadir el tipo de encriptamiento-->
    <!--se suele utilizar el método POST-->
    <input type="hidden" asp-for="alumno.Id" /><!--con esto sacamos los atributos, no los mostramos pero los tenemos-->
    <input type="hidden" asp-for="alumno.Foto" />
    <div class="form-group row">
        <label asp-for="alumno.Nombre" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="alumno.Nombre" class="form-control" placeholder="Nombre" />
            <span asp-validation-for="alumno.Nombre" class="text-danger"></span><!--Las validaciones se especifican en los modelos-->
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="alumno.Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="alumno.Email" class="form-control" placeholder="Email" />
            <span asp-validation-for="alumno.Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="alumno.CursoId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="alumno.CursoId" class="form-select mb-3" asp-items="Html.GetEnumSelectList<Curso>()">
                <!--Añadido el using RazorPages.Modelos en _ViewImports.cshtml-->
                <option value="Selecciona uno">Selecciona uno</option>
            </select>
            <span asp-validation-for="alumno.CursoId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Photo" class="custom-file-input" value="@Model.alumno.Foto" />
            <label class="custom-file-label">Click aquí para cambiar foto</label>
        </div>
    </div>
    <div class="form-group row col-sm-4 offset-4">
        <img class="imageThumbail" src="@photo"  asp-append-version="true" />
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Save</button>
            <a asp-page="/Alumnos/Index" class="btn btn-promary">Cancel</a>
        </div>
    </div>
</form>

@section Scripts{
    <!--<partial name="_ValidationScriptsPartial" /> <!--Esta linea es para que coja las validaciones en el lado del cliente, no es lo mejor-->
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                //este objeto (custom-file-input), su valor concatena con \\
                //y pop que es de jquery extrae de la pila algo que agustín no tiene muy claro
                var fileName = $(this).val().split("\\").pop();
                //al siguiente objeto label de estos le pones el fileName
                $(this).next('.custom-file-label').html(fileName);
            })
        })
    </script>

}

RazorPages1/RazorPages1/Pages/Alumnos/Index.cshtml
@page
@model RazorPages1.Pages.Alumnos.IndexModel
@{
}
<h1>Alumnos</h1>
<form method="get">
    <div class="input-group">
        <input class="form-control" asp-for="elementoABuscar" />
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary">Busca!</button>
        </div>
    </div>
</form>
<h3>@Model.Alumnos.Count()</h3><!--ponemos la arroba para trabajar con ASP-->
<div class="col-sm-8">
    <!--await Component.InvokeAsync("AlumnosCursoContar")-->
    @await Component.InvokeAsync("AlumnoCurso")
</div>
<div class="card-group">
    @foreach(var alumno in Model.Alumnos)
    //ponemos var por comodidad pero se podría poner Alumno, que sería más específico, pero
    // este lenguaje traga
    {
        var photo = "~/images/" + (alumno.Foto ?? "noimage.jpg");
        <div class="card m-3" style="min-width: 18rem; max-width:30%">
            <div class="card-header">
                <h3>@alumno.Nombre</h3>
            </div>
            <img class="card-img-top mx-auto imageThumbail" asp-append-version="true" src="@photo">
            <div class="card-footer text-center">
                <!--Aquí creamos un enlace a la pagina de detalles, pasándole un entero con la identificación del alumno-->
                <a asp-page="/Alumnos/Details" asp-route-ID="@alumno.Id" class="btn btn-primary m1">View</a>
                <a asp-page="/Alumnos/Edit" asp-route-ID="@alumno.Id" class="btn btn-primary m1">Edit</a>
                <a asp-page="/Alumnos/Delete" asp-route-ID="@alumno.Id" class="btn btn-danger m-1">Erase</a>
            </div>
        </div>
    }
</div>

RazorPages1/RazorPages1/Pages/Alumnos/Index2.cshtml
@page
@model RazorPages1.Pages.Alumnos.Index2Model
@{
    <script>$("select").prop("selectedIndex", 0);</script>
}

<h1>Alumnos</h1>
<form asp-action="edit" asp-controller="application" method="get">
    <div class="input-group">
        <label class="col-sm-2 col-form-label" asp-for="elementoABuscar">Curso: </label>
        <select class='form-select mb-3' asp-for="elementoABuscar" asp-items="@Html.GetEnumSelectList<Curso>()">
            <option value=null selected>Selecciona curso ...</option>
        </select>
    </div>
    <div class="input-group-append">
        <button type="submit" class="btn btn-primary">Busca!</button>
    </div>
</form>
<br />
<br />
<h3>@Model.Alumnos.Count()</h3><!--ponemos la arroba para trabajar con ASP-->
<div class="col-sm-8">
    <!--await Component.InvokeAsync("AlumnosCursoContar")-->
    @await Component.InvokeAsync("AlumnoCurso")
</div>
<div class="card-group">
    @foreach (var alumno in Model.Alumnos)
    //ponemos var por comodidad pero se podría poner Alumno, que sería más específico, pero
    // este lenguaje traga
    {
        var photo = "~/images/" + (alumno.Foto ?? "noimage.jpg");
        <div class="card m-3" style="min-width: 18rem; max-width:30%">
            <div class="card-header">
                <h3>@alumno.Nombre</h3>
            </div>
            <img class="card-img-top mx-auto imageThumbail" asp-append-version="true" src="@photo">
            <div class="card-footer text-center ">
                <!--Aquí creamos un enlace a la pagina de detalles, pasándole un entero con la identificación del alumno-->
                <a asp-page="/Alumnos/Details" asp-route-ID="@alumno.Id" class="btn btn-primary m1">View</a>
                <a asp-page="/Alumnos/Edit" asp-route-ID="@alumno.Id" class="btn btn-primary m1">Edit</a>
                <a asp-page="/Alumnos/Delete" asp-route-ID="@alumno.Id" class="btn btn-danger m-1">Erase</a>
            </div>

        </div>
    }
</div>